### ISSUE TITLE
Doesn't work with support Fragment

### ISSUE THREAD

**Issue by felipecsl** [f2prateek/bundler#3]
I didn't realize we set this up with `android.app.Fragment` and when I tried to used it didnt work since I'm on the support Fragment haha.
Ideas: 
1. Add another FragmentBuilder for support v4 namespace;
2. Instead of relying on the actual fragment class, create an interface, say `Argumentable` that has the method `setArguments` and have your fragments implement that, even though that's not 100% ideal.

I'm in favor of option 2. Ideas?

**Comment by f2prateek** [comment]
I'd go for 1, it's less work for someone newly integrating this library.
